default_context:
  project_name: 'coffee_shop'
  project_slug: 'coffee_shop'
  domain_main: 'coffee_shop.com'
  domain_staging: 'stag.coffee_shop.com'
  docker_swarm_stack_name_main: 'coffee_shop-com'
  docker_swarm_stack_name_staging: 'stag-coffee_shop-com'
  secret_key: '2623e8edc5694622deed7b02ac172520016cf48d571ee486529fe8cc15435b4c'
  first_superuser: 'admin@coffee_shop.com'
  first_superuser_password: '9254ae6442d645f76b3848296539a502790aeb35c9761ecfff56fceace2d6d95'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.coffee_shop.com", "https://stag.coffee_shop.com", "https://coffee_shop.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@coffee_shop.com'
  postgres_password: 'c2d6ac5f97587f68a2af85af71649b20da66da08161f9d98033d3d11f009f432'
  pgadmin_default_user: 'admin@coffee_shop.com'
  pgadmin_default_user_password: '9254ae6442d645f76b3848296539a502790aeb35c9761ecfff56fceace2d6d95'
  traefik_constraint_tag: 'coffee_shop.com'
  traefik_constraint_tag_staging: 'stag.coffee_shop.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:9254ae6442d645f76b3848296539a502790aeb35c9761ecfff56fceace2d6d95'
  sentry_dsn: ''
  docker_image_prefix: 'coffee_shop_project'
  docker_image_backend: 'coffee_shop_project/backend'
  docker_image_celeryworker: 'coffee_shop_project/celeryworker'
  docker_image_frontend: 'coffee_shop_project/frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
